version: '3.6'

services:
  docker.version_backend:
    image: ${DOCKER_REGISTRY-}versionmanagement_backend
    container_name: docker.version_backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
    ports:
      - "4000:80"
    depends_on:
      - docker.postgres
    networks:
      - version-net
      - nginx-net
    volumes:
      - /home/zhengxi/docker_volume/dotnet/versionmanagement/appsettings.Development.json:/app/appsettings.Development.json
      - /home/zhengxi/docker_volume/dotnet/versionmanagement/Logs:/app/Logs

  docker.version_frontend:
     image: ${DOCKER_REGISTRY-}versionmanagement_frontend
     container_name: docker.version_frontend
     restart: always
     build:
      context: ./Vue 
     depends_on: 
      - docker.version_backend
     networks:
      - version-net
      - nginx-net

  docker.version_postgres:
    image: postgres:alpine
    container_name: docker.version_postgres
    ports: 
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=123456
      - pgdata=/var/lib/postgresql/data
    volumes:
      - /home/zhengxi/docker_volume/postgres/postgres.versionmanagement:/var/lib/postgresql/data
    networks:
      - version-net

networks:
  version-net:
    driver: bridge
  nginx-net:
    external: true


  
   
    